language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - clang-format-5.0
      - g++-7

install:
 - pip install --user conan
 - conan user

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
 - make VERBOSE=1
 - cd ..
 - ./run-clang-format.py -r src
